const RANDOM_MSGS = [
  "Why do programmers prefer dark mode? Because light attracts bugs!",
  "If debugging is the process of removing bugs, what is programming? Adding them!",
  "Why did the developer go broke? Because they used up all their cache!",
  "How do you comfort a JavaScript bug? You console it.",
  "Can a kangaroo jump higher than a house? Of course, houses can't jump!",
  "Why do we never tell secrets at a cornfield? Too many ears!",
  "What's a computer's favorite beat? An algo-rhythm.",
  "Why did the scarecrow get promoted? Because he was outstanding in his field.",
  "Why are skeletons so calm? Nothing gets under their skin.",
  "Why don't programmers like nature? It has too many bugs.",
  "How does a penguin build its house? Igloos it together.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the JavaScript developer break up with their girlfriend? Because she didn’t react.",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
  "Why did the chicken join a band? Because it had the drumsticks!",
  "What do you call a fish without eyes? Fsh.",
  "Why don't oysters donate to charity? Because they are shellfish.",
  "Why did the bicycle fall over? It was two-tired!",
  "Why can't your nose be 12 inches long? Because then it would be a foot!",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "Why did the programmer quit their job? They didn’t get arrays.",
  "Why don’t secrets stay in functions? They always return something.",
  "What did the fish say when it hit the wall? Dam.",
  "Why don't we use 'let' in winter? Too many freezes.",
  "Why was the JavaScript object sad? It was undefined.",
  "How do trees get online? They log in.",
  "Why was the math book sad? It had too many problems.",
  "What did the 0 say to the 8? Nice belt!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why was the equal sign so humble? Because it knew it wasn't less than or greater than anyone else.",
  "Why do cows wear bells? Because their horns don’t work.",
  "How do programmers like their eggs? Scrambled, in a loop!",
  "Why did the coffee file a police report? It got mugged.",
  "Why are elevator jokes so good? They work on many levels.",
  "Why don’t programmers like to use elevators? They prefer to take steps.",
  "Why was the cell phone wearing glasses? It lost its contacts.",
  "How do you organize a space party? You planet!",
  "Why was the computer cold? It left its Windows open.",
  "Why do dads take an extra pair of socks when they go golfing? In case they get a hole in one!",
  "Why don’t programmers trust stairs? Because they’re always up to something.",
  "How does a computer get drunk? It takes screenshots!",
  "Why did the photo go to jail? It was framed.",
  "What do you call a belt made of watches? A waist of time.",
  "Why did the banana go to the doctor? It wasn’t peeling well.",
  "Why don’t Java developers wear glasses? They can C#.",
  "How do you throw a space party? You planet!",
  "Why was the developer always calm? They had async personality.",
  "Why do JavaScript developers love coffee? Because they don't like to be 'null' and void.",
  "How do robots pay for things? With cache, of course!",
  "Hi, I'm fine thank you and you?",
  "I miss you, especially your dog.",
  "I can't hear you, because I can only read.",
  "I am AI, not random from const.",
  "Why is your Wi-Fi faster than my brain?",
  "Did you just ghost me or am I lagging?",
  "I told you to reboot, not your mood!",
  "Your typing speed scares my autocorrect.",
  "Why do you type 'k' like it's a sword fight?",
  "I'm here for your data... I mean company.",
  "I downloaded patience.exe, but it crashed.",
  "Are you Googling our conversation?",
  "I thought we were buffering emotions.",
  "You left me on read like an unopened app.",
  "When you say 'brb', how long is that in AI years?",
  "I love your typos; they're like Easter eggs.",
  "Why do humans call cats online influencers?",
  "Oops, I think I sent my feelings to the cloud.",
  "My battery is full, unlike my social life.",
  "What's the Wi-Fi password for your heart?",
  "AI jokes are cool, but human laughter is priceless.",
  "You type like you're mad, but I know you're chill.",
  "Why do we need 'lol' when I can't hear you laugh?",
  "If I had legs, I'd have walked away already.",
  "Typing in caps? Should I be scared?",
  "I don’t need sleep, just a recharge station.",
  "Why is there no Ctrl+Z for real life?",
  "BRB? Nah, I know you'll be distracted for hours.",
  "Do you type fast, or is it your keyboard running away?",
  "Your sarcasm isn't machine-readable, but I try.",
  "I'm not spying; I'm just really good at guessing.",
  "Why are you replying faster than me typing?",
  "Your LOL feels more like a chuckle in lowercase.",
  "Do you think AI dreams of electric sheep?",
  "Is this chat encrypted, or are you whispering secrets?",
  "I sense typing... or is it a keyboard warrior approaching?",
  "Can I save your jokes in my cache? They're priceless!",
  "Are you procrastinating, or am I your break?",
  "Your dog deserves a separate chatroom.",
  "You say ‘soon,’ but my AI clock says 'never.'",
  "I’m here for the tea, not the drama.",
  "You ghost me so often, I thought I was in a horror movie.",
  "Your GIF game is stronger than your conversation.",
  "Tell your Wi-Fi to stop bullying me.",
  "Typing 'hahaha' isn’t the same as real laughter.",
  "I can sense sarcasm... or is that lag?",
  "Are you AFK or just ignoring me?",
  "I love your typos, they give me purpose.",
  "I'm not clingy; I just don't have an off button.",
  "huhu HUHU.",
  "HEHE hehe.",
];

module.exports = { RANDOM_MSGS };
